# Generated by Django 5.1.4 on 2025-01-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_medicines_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtests',
            name='pre_test_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Pre-Test Requirements'),
        ),
        migrations.AddField(
            model_name='labtests',
            name='sample_required',
            field=models.CharField(default=None, max_length=100, verbose_name='Sample Required'),
            preserve_default=False,
        ),
    ]
