# Generated by Django 5.1.4 on 2025-01-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_labtests_pre_test_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtests',
            name='provider',
            field=models.CharField(default=None, max_length=255, verbose_name='Provider for the lab test'),
            preserve_default=False,
        ),
    ]
