# Generated by Django 5.1.4 on 2025-01-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_labtests_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='name',
            field=models.CharField(help_text='Name of the medicine', max_length=255, unique=True, verbose_name='Medicine Name'),
        ),
    ]
