# Generated by Django 5.1.4 on 2025-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_medicines_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlistedLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test Name')),
            ],
        ),
        migrations.CreateModel(
            name='UnlistedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medicine', max_length=255, unique=True, verbose_name='Medicine Name')),
            ],
        ),
        migrations.AddField(
            model_name='medicines',
            name='customTiming',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicines',
            name='timings',
            field=models.CharField(choices=[('before_food', 'before_food'), ('after_food', 'after_food'), ('custom', 'custom')], default='after_food', max_length=11, verbose_name='Timing'),
            preserve_default=False,
        ),
    ]
