# Generated by Django 5.1.4 on 2025-01-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_unlistedlabtest_unlistedmedicine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='customTiming',
        ),
        migrations.AddField(
            model_name='medicines',
            name='customTimingDescription',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
