# Generated by Django 5.1.4 on 2025-01-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_remove_medicines_customtiming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='customTimingDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Description for Custom timing if selected'),
        ),
    ]
