# Generated by Django 5.1.4 on 2025-01-30 17:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_alter_medicines_customtimingdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='customTimingDescription',
            new_name='custom_timing_description',
        ),
        migrations.RenameField(
            model_name='medicines',
            old_name='sideEffects',
            new_name='side_effects',
        ),
        migrations.AddField(
            model_name='unlistedmedicine',
            name='custom_timing_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description for Custom timing if selected'),
        ),
        migrations.AddField(
            model_name='unlistedmedicine',
            name='duration_unit',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months')], default='Days', max_length=6, verbose_name='Duration Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unlistedmedicine',
            name='duration_value',
            field=models.IntegerField(default=0, help_text='Duration value based on the selected unit', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unlistedmedicine',
            name='frequency',
            field=models.IntegerField(default=0, help_text='Number of times the medicine should be taken per day', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unlistedmedicine',
            name='timings',
            field=models.CharField(choices=[('before_food', 'before_food'), ('after_food', 'after_food'), ('custom', 'custom')], default='before_food', max_length=11, verbose_name='Timing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicine_Stock', to='pharmacy.medicines', verbose_name='Medicine Details'),
        ),
        migrations.AddConstraint(
            model_name='unlistedmedicine',
            constraint=models.CheckConstraint(condition=models.Q(('frequency__gte', 1)), name='check_valid_frequency_unlisted_medicines'),
        ),
        migrations.AddConstraint(
            model_name='unlistedmedicine',
            constraint=models.CheckConstraint(condition=models.Q(('duration_value__gte', 1)), name='check_valid_duration_value_unlisted_medicines'),
        ),
    ]
