# Generated by Django 5.1.4 on 2025-02-02 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_alter_prescribedlabtest_status'),
        ('pharmacy', '0016_rename_customtimingdescription_medicines_custom_timing_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlistedPrescribedMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medicine', max_length=255, unique=True, verbose_name='Medicine Name')),
                ('frequency', models.IntegerField(help_text='Number of times the medicine should be taken per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_value', models.IntegerField(help_text='Duration value based on the selected unit', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_unit', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months')], max_length=6, verbose_name='Duration Unit')),
                ('timings', models.CharField(choices=[('Before Food', 'Before Food'), ('After Food', 'After Food'), ('Custom', 'Custom')], max_length=11, verbose_name='Timing')),
                ('custom_timing_description', models.TextField(blank=True, null=True, verbose_name='Description for Custom timing if selected')),
            ],
        ),
        migrations.RenameModel(
            old_name='UnlistedLabTest',
            new_name='UnlistedPrescribedLabTests',
        ),
        migrations.DeleteModel(
            name='UnlistedMedicine',
        ),
        migrations.AlterField(
            model_name='medicines',
            name='timings',
            field=models.CharField(choices=[('Before Food', 'Before Food'), ('After Food', 'After Food'), ('Custom', 'Custom')], max_length=11, verbose_name='Timing'),
        ),
        migrations.AddConstraint(
            model_name='unlistedprescribedmedicines',
            constraint=models.CheckConstraint(condition=models.Q(('frequency__gte', 1)), name='check_valid_frequency_unlisted_medicines'),
        ),
        migrations.AddConstraint(
            model_name='unlistedprescribedmedicines',
            constraint=models.CheckConstraint(condition=models.Q(('duration_value__gte', 1)), name='check_valid_duration_value_unlisted_medicines'),
        ),
    ]
