# Generated by Django 5.1.4 on 2025-02-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_unlistedprescribedlabtests_and_more'),
        ('pharmacy', '0017_unlistedprescribedmedicines_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnlistedPrescribedLabTests',
        ),
        migrations.DeleteModel(
            name='UnlistedPrescribedMedicines',
        ),
    ]
