# Generated by Django 5.1.4 on 2024-12-28 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_remove_patientuser_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='user',
        ),
        migrations.AddField(
            model_name='patientuser',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='primary_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
