# Generated by Django 5.1.4 on 2024-12-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_patientuser_user_patientuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='username',
        ),
    ]
