# Generated by Django 5.1.4 on 2024-12-28 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_remove_patientuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_assigned',
        ),
        migrations.AddField(
            model_name='appointment',
            name='token_assigned',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Token Assigned'),
        ),
    ]
