# Generated by Django 5.1.4 on 2024-12-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_remove_appointment_time_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason_for_visit',
        ),
    ]
