# Generated by Django 5.1.4 on 2025-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_remove_appointment_reason_for_visit'),
        ('pharmacy', '0013_unlistedlabtest_unlistedmedicine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='customTiming',
        ),
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='timings',
        ),
        migrations.AddField(
            model_name='prescription',
            name='unlistedLabTests',
            field=models.ManyToManyField(blank=True, related_name='prescription', to='pharmacy.unlistedlabtest', verbose_name='Prescribed Unlisted Lab Tests'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='unlistedMedicines',
            field=models.ManyToManyField(blank=True, related_name='prescription', to='pharmacy.unlistedmedicine', verbose_name='Prescribed Unlisted Medicines'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='prescription', to='doctor.prescribedmedicine', verbose_name='Prescribed Medicines'),
        ),
    ]
