# Generated by Django 5.1.4 on 2025-01-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_remove_prescribedmedicine_customtiming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='digital_signature',
        ),
    ]
