# Generated by Django 5.1.4 on 2025-01-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_remove_prescription_digital_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescribedlabtest',
            old_name='labtest',
            new_name='lab_test',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='labtests',
            new_name='lab_tests',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='unlistedLabTests',
            new_name='unlisted_lab_tests',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='unlistedMedicines',
            new_name='unlisted_medicines',
        ),
    ]
