# Generated by Django 5.1.4 on 2025-01-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_rename_labtest_prescribedlabtest_lab_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedlabtest',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Test Date'),
        ),
    ]
