# Generated by Django 5.1.4 on 2025-02-01 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_alter_prescribedlabtest_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='duration_value',
            field=models.FloatField(help_text='Duration value based on the selected unit', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
