# Generated by Django 5.1.4 on 2025-02-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_alter_prescribedmedicine_duration_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedlabtest',
            name='status',
            field=models.CharField(choices=[('prescribed', 'Prescribed'), ('Sample Collected', 'Sample Collected'), ('Report Collected', 'Report Collected'), ('Patient Informed', 'Patient Informed')], default='Prescribed', max_length=16, verbose_name='Test Status'),
        ),
    ]
