# Generated by Django 5.1.4 on 2025-02-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_alter_prescribedlabtest_status'),
        ('pharmacy', '0017_unlistedprescribedmedicines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='unlisted_medicines',
            field=models.ManyToManyField(blank=True, related_name='prescription', to='pharmacy.unlistedprescribedmedicines', verbose_name='Prescribed Unlisted Medicines'),
        ),
    ]
