# Generated by Django 5.1.4 on 2025-02-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_alter_prescription_unlisted_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedicine',
            name='status',
            field=models.CharField(choices=[('Prescribed', 'Prescribed'), ('Dispensed', 'Dispensed'), ('Not Available', 'Not Available')], default='Prescribed', max_length=13, verbose_name='Medicine Status'),
        ),
        migrations.AlterField(
            model_name='prescribedlabtest',
            name='status',
            field=models.CharField(choices=[('prescribed', 'Prescribed'), ('Sample Collected', 'Sample Collected'), ('Report Collected', 'Report Collected'), ('Patient Informed', 'Patient Informed')], default='Prescribed', max_length=16, verbose_name='Lab Test Status'),
        ),
    ]
