# Generated by Django 5.1.4 on 2025-02-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_prescribedmedicine_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedlabtest',
            name='status',
            field=models.CharField(choices=[('Prescribed', 'Prescribed'), ('Sample Collected', 'Sample Collected'), ('Report Collected', 'Report Collected'), ('Patient Informed', 'Patient Informed')], default='Prescribed', max_length=16, verbose_name='Lab Test Status'),
        ),
    ]
