# Generated by Django 5.1.4 on 2025-02-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_alter_prescribedlabtest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedlabtest',
            name='sample_tracking_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
