# Generated by Django 5.1.4 on 2025-02-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_prescription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='lab_tests_completed',
            field=models.BooleanField(default=False, help_text='Indicates whether all prescribed lab tests (both listed and unlisted) have been completed (samples collected) or the patient has been informed about any unavailability.'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines_fulfilled',
            field=models.BooleanField(default=False, help_text='Indicates whether all prescribed medicines (both listed and unlisted) have been dispensed or the patient has been informed about any unavailability.'),
        ),
    ]
