# Generated by Django 5.1.4 on 2025-02-03 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_prescription_lab_tests_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlistedPrescribedLabTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test Name')),
            ],
        ),
        migrations.AlterField(
            model_name='prescription',
            name='unlisted_lab_tests',
            field=models.ManyToManyField(blank=True, related_name='prescription', to='doctor.unlistedprescribedlabtests', verbose_name='Prescribed Unlisted Lab Tests'),
        ),
        migrations.CreateModel(
            name='UnlistedPrescribedMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medicine', max_length=255, unique=True, verbose_name='Medicine Name')),
                ('frequency', models.IntegerField(help_text='Number of times the medicine should be taken per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_value', models.IntegerField(help_text='Duration value based on the selected unit', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_unit', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months')], max_length=6, verbose_name='Duration Unit')),
                ('timings', models.CharField(choices=[('Before Food', 'Before Food'), ('After Food', 'After Food'), ('Custom', 'Custom')], max_length=11, verbose_name='Timing')),
                ('custom_timing_description', models.TextField(blank=True, null=True, verbose_name='Description for Custom timing if selected')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('frequency__gte', 1)), name='check_valid_frequency_unlisted_medicines'), models.CheckConstraint(condition=models.Q(('duration_value__gte', 1)), name='check_valid_duration_value_unlisted_medicines')],
            },
        ),
        migrations.AlterField(
            model_name='prescription',
            name='unlisted_medicines',
            field=models.ManyToManyField(blank=True, related_name='prescription', to='doctor.unlistedprescribedmedicines', verbose_name='Prescribed Unlisted Medicines'),
        ),
    ]
