# Generated by Django 5.1.4 on 2025-02-03 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_unlistedprescribedlabtests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='previous_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctor.appointment', verbose_name='Previous Appointment'),
        ),
    ]
