# Generated by Django 5.1.4 on 2025-02-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_appointment_previous_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedlabtest',
            name='report_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
