# Generated by Django 5.1.4 on 2025-02-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_prescribedlabtest_report_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='status',
        ),
    ]
