# Generated by Django 5.1.4 on 2025-02-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0031_remove_prescribedmedicine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedlabtest',
            name='attachment',
        ),
    ]
