# Generated by Django 5.1.4 on 2025-02-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0032_remove_prescribedlabtest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='additonal_information',
            field=models.TextField(blank=True, help_text='Additional Information for the patient', null=True, verbose_name='Additional Information'),
        ),
    ]
