# Generated by Django 5.1.4 on 2025-02-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0033_alter_prescription_additonal_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='additonal_information',
            new_name='additional_information',
        ),
    ]
