# Generated by Django 5.1.4 on 2025-02-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_rename_additonal_information_prescription_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='paid',
            field=models.BooleanField(default=False, help_text='If the patient has paid or not.'),
        ),
    ]
