# Generated by Django 5.1.4 on 2025-02-04 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_prescription_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicines_cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
            preserve_default=False,
        ),
    ]
