# Generated by Django 5.1.3 on 2025-02-10 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_prescription_medicines_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='medical_history',
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines_cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
