# Generated by Django 5.1.4 on 2024-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_delete_specializationavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Pharmacy', 'Pharmacy'), ('FrontDesk', 'FrontDesk')], max_length=9),
        ),
    ]
