# Generated by Django 5.1.4 on 2025-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Doctor', 'Doctor'), ('Pharmacy', 'Pharmacy'), ('FrontDesk', 'FrontDesk')], max_length=13),
        ),
    ]
